export const ROUTES_PATHS = {
    ADMIN: "/admin/manage",
    ADMIN_TICKET: "/admin/manage/ticket",
    ADMIN_CHANGE: "/admin/manage/change",
    ADMIN_PROBLEM: "/admin/manage/problem",
    ADMIN_REPORT: "/admin/manage/report",
    ADMIN_REPORT_PREVIEW: "/admin/manage/report/preview",
    ADMIN_SETTING: "/admin/manage/setting",
    ADMIN_CONTACT: "/admin/manage/contact",
    ADMIN_ROLE: "/admin/manage/role",
    ADMIN_USERS: "/admin/manage/users",
    ADMIN_GROUPS: "/admin/manage/groups",
    ADMIN_GROUPS_EDIT: "/admin/manage/groups/edit/:id",
    ADMIN_ROLE_EDIT: "/admin/manage/role/edit/:id",
    ADMIN_STATISTICS: "/admin/manage/statistics",
    ADMIN_SERVICE_REQUEST_REPORT: "/admin/manage/report/service-request",
    ADMIN_ROLE_PERMISSION_ADD: "/admin/manage/role/permission",
};