export const URL = {
  ROLE_URL: "api/Roles",
  SERVICE_CATEGORY_URL: "api/ServiceCategories",
  USER_URL: "api/Users",
  COMMENT_URL: "api/Comments",
  REQUEST_TICKET_URL: "api/RequestTickets",
  DASHBOARD_URL: "api/Dashboards",
  SERVICE_ITEM_URL: "api/ServiceItems",
  SERVICE_ITEM_EXT_URL: "api/ServiceItemCustomFields",
  GROUP_URL: "api/Groups",
  REQUEST_TICKET_EXT_URL: "api/RequestTicketExts",
  QUERY_URL: "api/Queries",
  SLA_URL: "api/Slas",
  SLA_METRIC_URL: "api/Slametrics",
  WORKFLOW_URL: "api/Workflows",
  WORKFLOW_TASK_URL: "api/WorkflowTasks",
  WORKFLOW_TRANSITION_URL: "api/WorkflowTransitions",
  WORKFLOW_ASSIGNMENT_URL: "api/WorkflowAssignments",
  CUSTOM_FIELD_URL: "api/CustomFields",
  REQUEST_TICKET_HIS_URL: "api/RequestTicketHistories",
};
